### ISSUE TITLE
src/page目录下面两个文件下面的main.js文件中import Vue from 'vue' import App from './index'这句是不是有问题，没法引入啊，

### ISSUE THREAD

**Issue by zchuichaohui** [jrainlau/taxi-together-client#2]

**Comment by jrainlau** [comment]
请贴出具体错误

**Comment by zchuichaohui** [comment]
本地运行，报这个问题，看了一下感觉是import App from './index'  这句话有问题，
![default](https://user-images.githubusercontent.com/21101947/39342892-adf731f2-4a0c-11e8-942c-3a41ad6b5fad.jpg)

**Comment by jrainlau** [comment]
有啥问题吗？已经在正常跑了呀

**Comment by zchuichaohui** [comment]
只是编译成功了，但是没有跑通，，访问http://localhost:8080  没反应啊，

**Comment by zchuichaohui** [comment]
![image](https://user-images.githubusercontent.com/21101947/39349266-e0f04fb0-4a2c-11e8-92c8-dca3a6798d24.png)

**Comment by jrainlau** [comment]
这是小程序，不能跑在浏览器

**Comment by zchuichaohui** [comment]
那这个用小程序开发工具也打不开啊，你们都是用什么打开运行的

**Comment by zchuichaohui** [comment]
感谢啊，我才了解，原来是vue开发，webpack打包生成dist文件，然后用小程序开发工具打开dist文件是吧，

**Comment by jrainlau** [comment]
对的

**Comment by zchuichaohui** [comment]
那这个项目的调试怎么搞啊，总不能每次修改一点东西，先打包生成dist文件，再打开小程序看效果吧，

**Comment by jrainlau** [comment]
请查看mpvue文档
